## QC: Stream Temperature Statistics

Spot-check `wt_stats.nc` by pulling 20 random stream IDs and displaying all statistics in tables. Goal is to verify values are in plausible ranges — not a formal validation.

In [4]:
import xarray as xr
import numpy as np
import pandas as pd
import random
import sys
sys.path.insert(0, '..')
from luts_wt import wt_stat_var_dict

pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.2f}'.format)

In [5]:
# Change this path to the sanity-check output while the full run is pending
WT_STATS_PATH = '/beegfs/CMIP6/jdpaul3/arctic_rivers_data/wt_stats_05282026.nc'

ds = xr.open_dataset(WT_STATS_PATH)
print(ds)

<xarray.Dataset> Size: 506MB
Dimensions:                   (stream_id: 34208, model: 7, era: 2, source: 3)
Coordinates:
  * stream_id                 (stream_id) int64 274kB 81000004 ... 82001714
  * model                     (model) <U10 280B 'C2LE2' 'C2LE4' ... 'historical'
  * era                       (era) <U9 72B '1990-2021' '2034-2065'
  * source                    (source) <U25 300B 'original_gcm' ... 'gcm_diff...
Data variables: (12/44)
    wt_days_gt13_mean         (source, era, model, stream_id) timedelta64[ns] 11MB ...
    wt_days_gt18_mean         (source, era, model, stream_id) timedelta64[ns] 11MB ...
    wt_days_gt20_mean         (source, era, model, stream_id) timedelta64[ns] 11MB ...
    wt_mean_jan               (source, era, model, stream_id) float64 11MB ...
    wt_mean_feb               (source, era, model, stream_id) float64 11MB ...
    wt_mean_mar               (source, era, model, stream_id) float64 11MB ...
    ...                        ...
    wt_max_dec                (source, era, model, stream_id) float64 11MB ...
    wt_ann_max_temp_mean      (source, era, model, stream_id) float64 11MB ...
    wt_ann_max_temp_doy_mean  (source, era, model, stream_id) float64 11MB ...
    wt_7d_max_temp_mean       (source, era, model, stream_id) float64 11MB ...
    wt_7d_max_temp_doy_mean   (source, era, model, stream_id) float64 11MB ...
    wt_cdd_may_sept_mean      (source, era, model, stream_id) float64 11MB ...
Attributes:
    Data_Source:   {'Title': 'Alaskan river discharge, temperature, and clima...
    GCM_Metadata:  {'historical': {'Modeling Center': 'National Center for At...

In [6]:
random.seed(42)
all_stream_ids = ds.stream_id.values.tolist()
sample_ids = random.sample(all_stream_ids, min(20, len(all_stream_ids)))
print(f'Sampled {len(sample_ids)} stream IDs:', sample_ids)

Sampled 20 stream IDs: [81007640, 81001892, 81018674, 81016686, 81015222, 81009538, 81007044, 81006011, 81028553, 81002342, 81002209, 81006462, 81014892, 81015857, 81035388, 81001992, 81013581, 81028376, 81015018, 81030542]

In [7]:
def stats_table(ds, var_names, stream_ids, model, era, source='original_gcm'):
    """Return a DataFrame: rows = variables, columns = stream_ids."""
    rows = {}
    for var in var_names:
        units = wt_stat_var_dict[var]['units']
        row_label = f'{var}  [{units}]'
        vals = (
            ds[var]
            .sel(model=model, era=era, source=source)
            .sel(stream_id=stream_ids)
            .values
        )
        rows[row_label] = vals
    return pd.DataFrame(rows, index=stream_ids).T

## Threshold exceedance — days above 13 / 18 / 20 °C

**Expected ranges (historical, Alaska streams):** most streams 0–60 days above 13°C; fewer above 18°C; very few or zero above 20°C for cold headwater streams.

In [8]:
thresh_vars = ['wt_days_gt13_mean', 'wt_days_gt18_mean', 'wt_days_gt20_mean']

print('=== Historical 1990-2021 ===')
display(stats_table(ds, thresh_vars, sample_ids, 'historical', '1990-2021'))

print('\n=== C2LE2 1990-2021 ===')
display(stats_table(ds, thresh_vars, sample_ids, 'C2LE2', '1990-2021'))

print('\n=== C2LE2 2034-2065 (expect higher counts) ===')
display(stats_table(ds, thresh_vars, sample_ids, 'C2LE2', '2034-2065'))

=== Historical 1990-2021 ===

,81007640,81001892,81018674,81016686,81015222,81009538,81007044,81006011,81028553,81002342,81002209,81006462,81014892,81015857,81035388,81001992,81013581,81028376,81015018,81030542
wt_days_gt13_mean [days],11 days 18:00:00,0 days 00:44:38.400000,3 days 22:30:43.200000,13 days 03:44:38.400000,17 days 00:44:38.400000,6 days 09:00:00,32 days 21:44:38.400000,1 days 00:44:38.400000,0 days,20 days 09:00:00,25 days 09:44:38.400000,1 days 05:15:21.600000,0 days 02:15:21.600000,6 days 23:15:21.600000,0 days,27 days 18:44:38.400000,20 days 10:30:43.200000,0 days,10 days 07:29:16.800000,0 days
wt_days_gt18_mean [days],0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days
wt_days_gt20_mean [days],0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days

=== C2LE2 1990-2021 ===

,81007640,81001892,81018674,81016686,81015222,81009538,81007044,81006011,81028553,81002342,81002209,81006462,81014892,81015857,81035388,81001992,81013581,81028376,81015018,81030542
wt_days_gt13_mean [days],8 days 07:29:16.800000,0 days 14:15:21.600000,7 days 08:15:21.599999999,7 days,8 days 02:15:21.600000,6 days 03:44:38.400000,27 days 10:30:43.200000,1 days 09:00:00,0 days,27 days 14:15:21.600000,38 days 04:30:43.200000,1 days 21:00:00,0 days 06:00:00,4 days 03:00:00,0 days 13:29:16.800000,37 days 12:00:00,10 days 18:00:00,0 days,5 days 07:29:16.800000,0 days
wt_days_gt18_mean [days],0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days
wt_days_gt20_mean [days],0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days

=== C2LE2 2034-2065 (expect higher counts) ===

,81007640,81001892,81018674,81016686,81015222,81009538,81007044,81006011,81028553,81002342,81002209,81006462,81014892,81015857,81035388,81001992,81013581,81028376,81015018,81030542
wt_days_gt13_mean [days],26 days 21:44:38.400000,6 days 03:44:38.400000,25 days 18:00:00,27 days 16:30:43.199999999,31 days 11:15:21.600000,22 days 12:00:00,47 days 00:44:38.400000,8 days 12:00:00,0 days,47 days 21:44:38.400000,57 days 23:15:21.600000,9 days,2 days 03:44:38.400000,20 days 23:15:21.600000,2 days 22:30:43.200000,56 days 11:15:21.600000,35 days 17:15:21.600000,0 days,23 days 03:00:00,0 days 15:00:00
wt_days_gt18_mean [days],0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 12:44:38.400000,1 days 03:00:00,0 days,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,1 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00
wt_days_gt20_mean [days],0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00

## Monthly mean temperatures

**Expected pattern:** near 0.1°C in winter (Nov–Mar), warming through spring, peak in July/August, cooling through fall. Should not see values > ~25°C or < 0°C.

In [9]:
mean_vars = [f'wt_mean_{m}' for m in ['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec']]

print('=== Historical 1990-2021: monthly mean temperatures ===')
display(stats_table(ds, mean_vars, sample_ids, 'historical', '1990-2021'))

=== Historical 1990-2021: monthly mean temperatures ===

,81007640,81001892,81018674,81016686,81015222,81009538,81007044,81006011,81028553,81002342,81002209,81006462,81014892,81015857,81035388,81001992,81013581,81028376,81015018,81030542
wt_mean_jan [degC],2.04,3.23,1.35,2.10,1.90,1.23,1.11,1.47,2.01,2.94,3.16,1.40,1.68,1.94,2.12,2.75,1.90,1.59,2.06,1.99
wt_mean_feb [degC],1.90,2.92,1.32,1.95,1.78,1.19,1.10,1.41,1.81,2.67,2.88,1.35,1.57,1.81,1.91,2.50,1.77,1.43,1.90,1.80
wt_mean_mar [degC],1.91,2.94,1.50,2.02,1.88,1.40,1.26,1.50,1.85,2.75,2.91,1.45,1.65,1.90,1.95,2.62,1.88,1.52,1.96,1.83
wt_mean_apr [degC],2.09,3.08,2.35,2.83,2.64,1.99,2.00,1.82,2.07,3.01,3.07,1.85,2.05,2.66,2.25,3.02,2.74,2.06,2.60,2.15
wt_mean_may [degC],4.27,3.81,4.56,6.39,6.35,4.06,5.24,3.11,2.88,3.98,3.89,3.25,3.47,5.79,3.53,4.25,6.50,3.18,5.87,3.41
wt_mean_jun [degC],10.23,6.49,8.88,10.93,11.10,9.33,11.54,8.18,4.87,6.88,6.62,8.09,7.35,10.26,6.52,8.14,11.44,5.30,10.60,6.31
wt_mean_jul [degC],12.40,9.22,11.39,12.36,12.55,11.82,13.24,11.19,6.91,11.97,12.27,10.97,9.94,11.96,9.17,12.98,12.70,7.35,12.18,8.84
wt_mean_aug [degC],10.89,7.83,10.05,11.42,11.54,10.19,11.62,9.20,6.65,11.09,11.82,9.32,8.60,10.93,9.27,11.61,11.55,7.23,11.11,8.47
wt_mean_sep [degC],6.46,4.97,5.59,8.21,8.17,5.83,7.03,4.87,4.43,7.67,8.20,5.18,4.86,7.50,6.16,7.88,8.10,4.83,7.66,5.25
wt_mean_oct [degC],2.75,3.38,2.31,3.83,3.73,2.35,2.52,2.11,2.55,4.46,4.69,2.22,2.38,3.40,3.31,4.31,3.58,2.57,3.43,2.81
wt_mean_nov [degC],1.98,3.01,1.37,2.19,2.01,1.31,1.24,1.49,1.94,2.99,3.15,1.44,1.64,2.00,2.12,2.80,1.99,1.60,2.08,1.94
wt_mean_dec [degC],1.91,2.93,1.22,1.94,1.75,1.13,0.98,1.35,1.79,2.69,2.89,1.28,1.53,1.79,1.92,2.51,1.74,1.41,1.90,1.78

## Monthly min and max temperatures

Min should be at or near 0.1°C (model floor). Max should be the warmest average July/August across all years — slightly above the mean.

In [10]:
min_vars = [f'wt_min_{m}' for m in ['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec']]
max_vars = [f'wt_max_{m}' for m in ['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec']]

print('=== Historical 1990-2021: monthly min temperatures ===')
display(stats_table(ds, min_vars, sample_ids, 'historical', '1990-2021'))

print('\n=== Historical 1990-2021: monthly max temperatures ===')
display(stats_table(ds, max_vars, sample_ids, 'historical', '1990-2021'))

=== Historical 1990-2021: monthly min temperatures ===

,81007640,81001892,81018674,81016686,81015222,81009538,81007044,81006011,81028553,81002342,81002209,81006462,81014892,81015857,81035388,81001992,81013581,81028376,81015018,81030542
wt_min_jan [degC],1.95,3.05,0.61,1.92,1.73,0.95,0.80,1.26,1.71,2.73,2.98,1.07,1.45,1.73,1.91,2.38,1.68,1.17,1.90,1.79
wt_min_feb [degC],1.89,2.84,0.96,1.87,1.68,0.90,0.85,1.27,1.67,2.53,2.79,1.15,1.40,1.71,1.80,2.23,1.65,1.04,1.84,1.64
wt_min_mar [degC],1.89,2.87,0.88,1.88,1.75,1.17,0.84,1.28,1.66,2.62,2.84,1.10,1.45,1.74,1.85,2.40,1.67,1.05,1.85,1.69
wt_min_apr [degC],1.94,2.94,1.60,2.07,2.05,1.64,1.58,1.62,1.88,2.85,2.94,1.55,1.71,1.99,1.98,2.76,2.02,1.61,2.03,1.90
wt_min_may [degC],2.61,3.22,3.37,3.71,3.79,2.67,3.08,2.18,2.24,3.23,3.21,2.25,2.35,3.51,2.66,3.27,3.52,2.49,3.42,2.42
wt_min_jun [degC],8.53,5.23,7.63,8.94,9.03,7.30,10.04,6.20,3.88,4.99,4.89,6.35,5.97,8.31,5.28,5.29,9.82,4.45,8.54,5.09
wt_min_jul [degC],10.70,7.36,10.02,10.98,11.14,9.37,11.85,9.34,5.16,7.09,7.00,8.64,8.16,10.63,7.66,8.30,11.32,5.58,10.68,7.29
wt_min_aug [degC],7.63,5.56,8.18,9.59,9.88,6.78,8.70,5.88,4.83,7.49,8.19,6.33,6.13,8.81,7.17,8.09,9.58,5.65,9.11,6.62
wt_min_sep [degC],4.60,4.00,3.81,6.21,6.32,3.77,5.17,3.62,3.04,5.89,6.16,3.58,3.42,5.44,4.46,5.67,5.99,3.36,5.71,3.83
wt_min_oct [degC],2.10,3.02,1.74,2.55,2.54,1.51,1.62,1.63,1.99,3.21,3.36,1.66,1.81,2.26,2.54,2.92,2.30,1.79,2.38,2.11
wt_min_nov [degC],1.91,2.88,0.51,1.93,1.76,1.01,0.93,1.30,1.71,2.61,2.86,1.16,1.34,1.76,1.88,2.31,1.70,0.99,1.89,1.68
wt_min_dec [degC],1.89,2.85,0.43,1.87,1.68,0.90,0.77,1.17,1.67,2.56,2.82,1.05,1.38,1.70,1.81,2.31,1.62,1.08,1.84,1.63

=== Historical 1990-2021: monthly max temperatures ===

,81007640,81001892,81018674,81016686,81015222,81009538,81007044,81006011,81028553,81002342,81002209,81006462,81014892,81015857,81035388,81001992,81013581,81028376,81015018,81030542
wt_max_jan [degC],2.22,3.61,1.76,2.51,2.21,1.47,1.34,1.64,2.28,3.34,3.58,1.68,1.98,2.29,2.44,3.30,2.27,2.13,2.36,2.42
wt_max_feb [degC],1.92,3.00,1.66,2.10,1.89,1.36,1.36,1.54,2.10,2.81,2.98,1.49,1.75,1.98,2.04,2.68,1.95,1.80,2.02,2.06
wt_max_mar [degC],2.00,3.14,1.89,2.52,2.21,1.72,1.62,1.71,2.04,3.07,3.20,1.74,1.88,2.34,2.14,3.10,2.40,1.96,2.31,2.08
wt_max_apr [degC],2.72,3.26,2.90,3.85,3.48,2.60,2.98,2.12,2.41,3.41,3.40,2.31,2.41,3.57,2.78,3.69,3.81,2.51,3.44,2.72
wt_max_may [degC],6.54,4.95,6.04,8.28,8.20,5.86,7.83,4.62,3.69,5.80,5.29,4.88,5.04,7.78,4.79,6.11,8.85,4.20,7.88,4.72
wt_max_jun [degC],12.02,8.32,11.08,12.41,12.46,11.34,13.03,10.18,6.18,11.22,12.18,10.57,9.30,11.86,8.79,12.90,12.70,6.85,12.13,8.44
wt_max_jul [degC],13.44,11.57,13.22,13.54,13.65,13.41,14.09,12.80,9.88,16.43,17.08,12.60,12.14,13.47,11.78,16.87,13.74,10.40,13.44,11.41
wt_max_aug [degC],12.74,10.43,13.31,13.35,13.36,12.39,13.07,11.38,9.37,14.65,15.45,12.10,11.34,13.19,12.00,15.06,13.38,9.65,13.19,11.42
wt_max_sep [degC],8.15,5.96,7.21,9.79,9.84,7.22,8.90,6.30,5.50,9.91,10.52,6.62,5.89,8.99,8.44,10.66,9.86,5.80,9.32,6.65
wt_max_oct [degC],3.51,4.13,3.30,5.86,5.40,3.36,3.51,2.71,3.75,5.89,5.99,2.92,2.96,5.22,4.31,5.97,5.70,3.69,5.16,3.59
wt_max_nov [degC],2.20,3.28,1.93,2.72,2.49,1.73,1.59,1.66,2.37,3.44,3.55,1.82,2.16,2.44,2.50,3.23,2.65,2.51,2.47,2.71
wt_max_dec [degC],1.99,3.13,1.53,2.15,1.94,1.46,1.33,1.58,2.02,2.87,3.02,1.61,1.79,2.02,2.12,2.78,2.04,1.86,2.06,2.10

## Annual maximum daily temperature — magnitude and timing

**Magnitude:** should be the highest daily value of the year, above the monthly mean peak. Roughly 10–25°C for most Alaska streams.

**Julian day:** peak should fall in summer — roughly day 150–240 (early June to late August).

In [11]:
ann_vars = ['wt_ann_max_temp_mean', 'wt_ann_max_temp_doy_mean']

print('=== Historical 1990-2021 ===')
display(stats_table(ds, ann_vars, sample_ids, 'historical', '1990-2021'))

print('\n=== C2LE2 2034-2065 (expect slightly higher temps, similar DOY) ===')
display(stats_table(ds, ann_vars, sample_ids, 'C2LE2', '2034-2065'))

=== Historical 1990-2021 ===

,81007640,81001892,81018674,81016686,81015222,81009538,81007044,81006011,81028553,81002342,81002209,81006462,81014892,81015857,81035388,81001992,81013581,81028376,81015018,81030542
wt_ann_max_temp_mean [degC],13.15,10.77,12.91,13.04,13.23,13.01,14.05,12.33,8.30,14.60,15.22,12.39,11.20,12.81,11.01,15.53,13.39,8.81,12.93,10.39
wt_ann_max_temp_doy_mean [day of year],196.91,203.66,205.50,196.47,196.09,197.88,192.62,196.81,211.44,208.94,210.38,199.25,203.25,203.03,210.28,206.72,195.38,208.53,200.44,208.59

=== C2LE2 2034-2065 (expect slightly higher temps, similar DOY) ===

,81007640,81001892,81018674,81016686,81015222,81009538,81007044,81006011,81028553,81002342,81002209,81006462,81014892,81015857,81035388,81001992,81013581,81028376,81015018,81030542
wt_ann_max_temp_mean [degC],13.54,12.85,14.68,13.50,13.67,13.88,14.43,13.08,10.11,16.62,17.10,13.23,12.52,13.39,12.47,17.06,13.80,10.73,13.40,12.10
wt_ann_max_temp_doy_mean [day of year],194.56,198.50,195.06,192.88,193.47,193.66,191.59,195.25,212.91,201.19,201.12,196.69,194.78,194.72,201.78,199.19,191.41,206.94,192.69,206.91

## Maximum 7-day rolling average — magnitude and timing

**Magnitude:** should be slightly lower than the daily max (smoothed). **Julian day:** similar to daily max DOY — the 7-day window centers near the annual peak. Values will differ by a few days from `wt_ann_max_temp_doy_mean`.

In [12]:
roll_vars = ['wt_7d_max_temp_mean', 'wt_7d_max_temp_doy_mean']

print('=== Historical 1990-2021 ===')
display(stats_table(ds, roll_vars, sample_ids, 'historical', '1990-2021'))

print('\n=== Difference: daily max minus 7-day max (expect small positive values) ===')
diff = (
    ds['wt_ann_max_temp_mean'].sel(model='historical', era='1990-2021', source='original_gcm').sel(stream_id=sample_ids)
    - ds['wt_7d_max_temp_mean'].sel(model='historical', era='1990-2021', source='original_gcm').sel(stream_id=sample_ids)
).to_pandas().rename('daily_max - 7d_max  [degC]')
display(diff.to_frame().T)

=== Historical 1990-2021 ===

,81007640,81001892,81018674,81016686,81015222,81009538,81007044,81006011,81028553,81002342,81002209,81006462,81014892,81015857,81035388,81001992,81013581,81028376,81015018,81030542
wt_7d_max_temp_mean [degC],13.03,10.45,12.52,12.93,13.11,12.72,13.83,12.08,8.06,14.16,14.84,12.10,10.97,12.66,10.75,15.06,13.26,8.50,12.81,10.14
wt_7d_max_temp_doy_mean [day of year],197.91,205.25,206.81,198.66,197.50,199.56,194.34,196.31,211.16,209.69,210.38,200.28,202.97,203.97,209.78,206.88,195.94,210.75,200.41,208.56

=== Difference: daily max minus 7-day max (expect small positive values) ===

stream_id,81007640,81001892,81018674,81016686,81015222,81009538,81007044,81006011,81028553,81002342,81002209,81006462,81014892,81015857,81035388,81001992,81013581,81028376,81015018,81030542
daily_max - 7d_max [degC],0.12,0.32,0.38,0.10,0.12,0.29,0.21,0.26,0.24,0.44,0.38,0.29,0.23,0.15,0.26,0.47,0.13,0.30,0.12,0.25

## Cumulative degree days above 0°C (May–September)

**Expected range:** all values > 0 (minimum T_stream is 0.1°C × 153 May–Sept days ≈ 15 °C·days floor). Warm lowland streams could reach ~2000 °C·days. Cold headwater streams near the floor.

In [13]:
cdd_vars = ['wt_cdd_may_sept_mean']

print('=== Historical 1990-2021 ===')
display(stats_table(ds, cdd_vars, sample_ids, 'historical', '1990-2021'))

print('\n=== C2LE2 2034-2065 (expect higher CDD) ===')
display(stats_table(ds, cdd_vars, sample_ids, 'C2LE2', '2034-2065'))

=== Historical 1990-2021 ===

,81007640,81001892,81018674,81016686,81015222,81009538,81007044,81006011,81028553,81002342,81002209,81006462,81014892,81015857,81035388,81001992,81013581,81028376,81015018,81030542
wt_cdd_may_sept_mean [degC days],1354.59,990.06,1239.90,1509.19,1521.73,1262.59,1489.85,1119.82,788.45,1274.61,1311.67,1127.86,1048.49,1421.87,1061.28,1374.62,1539.20,854.25,1451.69,988.86

=== C2LE2 2034-2065 (expect higher CDD) ===

,81007640,81001892,81018674,81016686,81015222,81009538,81007044,81006011,81028553,81002342,81002209,81006462,81014892,81015857,81035388,81001992,81013581,81028376,81015018,81030542
wt_cdd_may_sept_mean [degC days],1517.16,1180.61,1486.58,1652.85,1659.08,1465.24,1641.18,1288.80,990.04,1593.88,1653.96,1312.60,1259.85,1578.85,1334.07,1668.37,1669.46,1084.64,1592.17,1277.27

## NaN structure checks

Verify the expected NaN patterns from the `source` dimension:
- `historical` model has no future projections → all-NaN in the `2034-2065` era for `original_gcm`
- `PGWh`/`PGWm` are future-only → all-NaN in the `1990-2021` era for `original_gcm`
- `gcm_diff` past era should always be all-NaN (by design)
- GCM models (C2LE*) should have data in both eras

In [14]:
sid = sample_ids[0]
check_var = 'wt_ann_max_temp_mean'

checks = {
    'historical / 2034-2065 / original_gcm  (expect NaN)':  ds[check_var].sel(model='historical', era='2034-2065', source='original_gcm', stream_id=sid).item(),
    'PGWh      / 1990-2021 / original_gcm  (expect NaN)':   ds[check_var].sel(model='PGWh',       era='1990-2021', source='original_gcm', stream_id=sid).item(),
    'PGWm      / 1990-2021 / original_gcm  (expect NaN)':   ds[check_var].sel(model='PGWm',       era='1990-2021', source='original_gcm', stream_id=sid).item(),
    'any model / 1990-2021 / gcm_diff      (expect NaN)':   ds[check_var].sel(model='C2LE2',      era='1990-2021', source='gcm_diff',      stream_id=sid).item(),
    'historical / 1990-2021 / original_gcm (expect value)': ds[check_var].sel(model='historical', era='1990-2021', source='original_gcm', stream_id=sid).item(),
    'C2LE2     / 1990-2021 / original_gcm  (expect value)': ds[check_var].sel(model='C2LE2',      era='1990-2021', source='original_gcm', stream_id=sid).item(),
    'C2LE2     / 2034-2065 / original_gcm  (expect value)': ds[check_var].sel(model='C2LE2',      era='2034-2065', source='original_gcm', stream_id=sid).item(),
    'C2LE2     / 2034-2065 / gcm_diff      (expect value)': ds[check_var].sel(model='C2LE2',      era='2034-2065', source='gcm_diff',      stream_id=sid).item(),
}

for label, val in checks.items():
    is_nan = np.isnan(val)
    expected_nan = 'expect NaN' in label
    status = 'OK' if is_nan == expected_nan else 'FAIL'
    print(f'[{status}]  {label}  →  {val}')

[OK]  historical / 2034-2065 / original_gcm  (expect NaN)  →  nan
[OK]  PGWh      / 1990-2021 / original_gcm  (expect NaN)  →  nan
[OK]  PGWm      / 1990-2021 / original_gcm  (expect NaN)  →  nan
[OK]  any model / 1990-2021 / gcm_diff      (expect NaN)  →  nan
[OK]  historical / 1990-2021 / original_gcm (expect value)  →  13.15
[OK]  C2LE2     / 1990-2021 / original_gcm  (expect value)  →  12.954
[OK]  C2LE2     / 2034-2065 / original_gcm  (expect value)  →  13.542
[OK]  C2LE2     / 2034-2065 / gcm_diff      (expect value)  →  0.5879999999999992


## original_gcm vs gcm_diff_applied_to_blaskey (2034–2065)

`gcm_diff_applied_to_blaskey` applies each GCM's delta (future − past) to the historical Blaskey baseline rather than using the raw GCM future value:
```
gcm_diff_applied_to_blaskey = historical_past + (gcm_future − gcm_past)
```
This comparison checks how much the two approaches diverge. Large `orig-adj` values mean the GCM and the historical Blaskey run disagree on the baseline, so the choice of source matters for the front end. Only GCM models (C2LE*) have non-NaN values for both sources in the future era.

In [ ]:

GCM_MODELS = ['C2LE2', 'C2LE4', 'C2LE7', 'C2LE9']

def comparison_table(ds, var_names, stream_ids, model, era='2034-2065'):
    """Side-by-side comparison of original_gcm vs gcm_diff_applied_to_blaskey.
    Returns a DataFrame with three row blocks per variable:
      - original   (raw GCM future)
      - adjusted   (historical Blaskey baseline + GCM delta)
      - orig-adj   (difference; positive = GCM runs warmer than bias-corrected)
    """
    rows = {}
    for var in var_names:
        units = wt_stat_var_dict[var]['units']
        orig = ds[var].sel(model=model, era=era, source='original_gcm').sel(stream_id=stream_ids).values
        adj  = ds[var].sel(model=model, era=era, source='gcm_diff_applied_to_blaskey').sel(stream_id=stream_ids).values
        rows[f'{var}  original  [{units}]'] = orig
        rows[f'{var}  adjusted  [{units}]'] = adj
        rows[f'{var}  orig-adj  [{units}]'] = orig - adj
    return pd.DataFrame(rows, index=stream_ids).T

In [16]:

stat_groups = [
    ('Threshold exceedance (days)',        thresh_vars),
    ('Monthly mean temperatures',          mean_vars),
    ('Annual max + 7-day rolling max',     ann_vars + roll_vars),
    ('Cumulative degree days (May–Sept)',   cdd_vars),
]

for model in GCM_MODELS:
    print(f'\n{"="*70}')
    print(f'  MODEL: {model}  |  era: 2034-2065')
    print(f'{"="*70}')
    for group_label, var_list in stat_groups:
        print(f'\n--- {group_label} ---')
        print('  rows: [variable  original], [variable  adjusted], [variable  orig-adj]')
        display(comparison_table(ds, var_list, sample_ids, model))

======================================================================
  MODEL: C2LE2  |  era: 2034-2065
======================================================================

--- Threshold exceedance (days) ---
  rows: [variable  original], [variable  adjusted], [variable  orig-adj]

,81007640,81001892,81018674,81016686,81015222,81009538,81007044,81006011,81028553,81002342,81002209,81006462,81014892,81015857,81035388,81001992,81013581,81028376,81015018,81030542
wt_days_gt13_mean original [days],26 days 21:44:38.400000,6 days 03:44:38.400000,25 days 18:00:00,27 days 16:30:43.199999999,31 days 11:15:21.600000,22 days 12:00:00,47 days 00:44:38.400000,8 days 12:00:00,0 days,47 days 21:44:38.400000,57 days 23:15:21.600000,9 days 00:00:00,2 days 03:44:38.400000,20 days 23:15:21.600000,2 days 22:30:43.200000,56 days 11:15:21.600000,35 days 17:15:21.600000,0 days,23 days 03:00:00,0 days 15:00:00
wt_days_gt13_mean adjusted [days],30 days 08:15:21.599999999,5 days 14:13:55.200000,22 days 08:15:21.599999999,33 days 20:15:21.600000,40 days 09:44:38.400000,22 days 17:15:21.600000,52 days 11:58:33.600000,8 days 03:44:38.400000,0 days,40 days 16:29:16.800000,45 days 04:29:16.800000,8 days 08:15:21.599999999,2 days 00:00:00,23 days 19:30:43.199999999,2 days 09:01:26.400000,46 days 18:00:00,45 days 09:46:04.799999999,0 days,28 days 03:00:00,0 days 15:00:00
wt_days_gt13_mean orig-adj [days],-4 days +13:29:16.800000001,0 days 13:30:43.200000,3 days 09:44:38.400000001,-7 days +20:15:21.599999999,-9 days +01:30:43.200000,-1 days +18:44:38.400000,-6 days +12:46:04.800000,0 days 08:15:21.600000,0 days,7 days 05:15:21.600000,12 days 18:46:04.800000,0 days 15:44:38.400000001,0 days 03:44:38.400000,-3 days +03:44:38.400000001,0 days 13:29:16.800000,9 days 17:15:21.600000,-10 days +07:29:16.800000001,0 days,-5 days +00:00:00,0 days 00:00:00
wt_days_gt18_mean original [days],0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 12:44:38.400000,1 days 03:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,1 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00
wt_days_gt18_mean adjusted [days],0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 12:44:38.400000,1 days 03:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,1 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00
wt_days_gt18_mean orig-adj [days],0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00
wt_days_gt20_mean original [days],0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00
wt_days_gt20_mean adjusted [days],0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00
wt_days_gt20_mean orig-adj [days],0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00

--- Monthly mean temperatures ---
  rows: [variable  original], [variable  adjusted], [variable  orig-adj]

,81007640,81001892,81018674,81016686,81015222,81009538,81007044,81006011,81028553,81002342,81002209,81006462,81014892,81015857,81035388,81001992,81013581,81028376,81015018,81030542
wt_mean_jan original [degC],2.12,3.40,1.61,2.35,2.12,1.40,1.34,1.61,2.21,3.21,3.38,1.61,1.80,2.18,2.18,3.10,2.16,1.85,2.25,2.14
wt_mean_jan adjusted [degC],2.09,3.31,1.41,2.26,2.05,1.33,1.20,1.52,2.15,3.17,3.35,1.45,1.74,2.09,2.16,3.00,2.04,1.74,2.18,2.09
wt_mean_jan orig-adj [degC],0.03,0.09,0.20,0.08,0.07,0.07,0.15,0.09,0.07,0.03,0.03,0.16,0.06,0.09,0.02,0.10,0.12,0.11,0.07,0.05
wt_mean_feb original [degC],1.94,3.02,1.52,2.16,1.94,1.33,1.28,1.51,1.99,2.81,2.99,1.50,1.66,2.01,1.96,2.71,1.99,1.68,2.05,1.93
wt_mean_feb adjusted [degC],1.92,2.98,1.38,2.07,1.86,1.30,1.18,1.47,1.90,2.74,2.93,1.44,1.61,1.92,1.94,2.60,1.90,1.54,1.99,1.85
wt_mean_feb orig-adj [degC],0.02,0.05,0.14,0.09,0.08,0.03,0.09,0.04,0.09,0.07,0.06,0.06,0.05,0.09,0.03,0.10,0.09,0.13,0.07,0.08
wt_mean_mar original [degC],1.97,3.03,1.78,2.35,2.13,1.53,1.55,1.64,2.05,2.88,3.02,1.62,1.78,2.21,2.04,2.82,2.19,1.81,2.20,2.01
wt_mean_mar adjusted [degC],1.93,2.98,1.55,2.12,1.96,1.47,1.35,1.56,1.91,2.84,2.99,1.51,1.68,2.00,1.96,2.75,1.98,1.57,2.03,1.85
wt_mean_mar orig-adj [degC],0.04,0.05,0.24,0.23,0.17,0.06,0.20,0.08,0.15,0.04,0.04,0.11,0.10,0.21,0.08,0.07,0.22,0.23,0.17,0.16
wt_mean_apr original [degC],2.43,3.28,2.85,3.66,3.33,2.43,2.58,2.08,2.36,3.35,3.40,2.16,2.35,3.36,2.58,3.46,3.52,2.46,3.28,2.57
wt_mean_apr adjusted [degC],2.31,3.21,2.62,3.28,3.02,2.27,2.36,1.98,2.25,3.25,3.31,2.03,2.21,3.07,2.45,3.31,3.23,2.32,3.00,2.38
wt_mean_apr orig-adj [degC],0.11,0.07,0.23,0.38,0.31,0.16,0.22,0.10,0.11,0.10,0.09,0.12,0.13,0.29,0.14,0.14,0.29,0.14,0.28,0.19
wt_mean_may original [degC],6.09,4.50,6.14,7.74,7.67,5.88,7.11,4.29,3.55,4.90,4.86,4.78,4.70,7.10,4.73,5.48,7.90,4.05,7.21,4.64
wt_mean_may adjusted [degC],5.30,4.31,5.59,7.30,7.21,5.15,6.27,3.82,3.33,4.38,4.37,4.22,4.22,6.69,4.34,4.73,7.51,3.77,6.81,4.12
wt_mean_may orig-adj [degC],0.79,0.19,0.55,0.44,0.46,0.73,0.84,0.47,0.21,0.52,0.48,0.56,0.48,0.41,0.39,0.75,0.39,0.29,0.40,0.53
wt_mean_jun original [degC],11.64,8.27,10.97,12.00,12.13,11.26,12.67,9.98,6.33,10.66,10.78,10.05,9.34,11.52,9.04,11.79,12.33,6.99,11.71,8.73
wt_mean_jun adjusted [degC],11.33,8.00,10.27,11.93,11.98,10.81,12.44,9.58,6.24,8.59,8.37,9.63,8.86,11.46,8.00,9.79,12.42,6.67,11.71,7.77
wt_mean_jun orig-adj [degC],0.31,0.27,0.70,0.06,0.15,0.45,0.23,0.40,0.09,2.07,2.41,0.41,0.48,0.06,1.04,2.00,-0.09,0.33,-0.01,0.97
wt_mean_jul original [degC],12.90,11.04,13.12,12.75,12.88,12.73,13.61,11.98,8.34,14.63,15.30,12.05,11.31,12.47,11.23,15.13,12.97,9.00,12.56,10.94
wt_mean_jul adjusted [degC],13.35,11.63,13.15,13.43,13.57,13.07,14.08,12.69,9.03,14.01,14.20,12.46,11.70,13.23,10.96,14.89,13.70,9.36,13.36,10.56
wt_mean_jul orig-adj [degC],-0.46,-0.59,-0.03,-0.67,-0.69,-0.34,-0.48,-0.71,-0.69,0.63,1.10,-0.41,-0.39,-0.76,0.27,0.24,-0.73,-0.36,-0.80,0.37
wt_mean_aug original [degC],11.25,8.71,11.19,11.83,11.92,10.80,11.94,9.76,8.06,12.42,13.14,9.75,9.53,11.44,10.70,12.65,11.89,8.79,11.49,10.28
wt_mean_aug adjusted [degC],11.77,8.97,11.52,12.64,12.76,11.14,12.46,10.26,8.66,12.00,12.68,10.13,10.03,12.28,10.95,12.44,12.74,9.07,12.44,10.19
wt_mean_aug orig-adj [degC],-0.52,-0.25,-0.32,-0.81,-0.83,-0.33,-0.52,-0.50,-0.60,0.42,0.46,-0.38,-0.50,-0.85,-0.25,0.22,-0.85,-0.28,-0.95,0.09
wt_mean_sep original [degC],7.69,6.03,7.11,9.70,9.61,7.19,8.29,6.08,6.05,9.45,9.95,6.24,6.28,9.06,7.88,9.46,9.46,6.59,9.07,7.13
wt_mean_sep adjusted [degC],7.62,5.88,6.86,9.94,9.82,6.91,8.26,5.95,6.20,8.88,9.38,6.09,6.13,9.27,7.67,9.06,9.79,6.56,9.42,6.82
wt_mean_sep orig-adj [degC],0.07,0.15,0.25,-0.24,-0.21,0.28,0.03,0.13,-0.15,0.57,0.56,0.15,0.15,-0.21,0.21,0.40,-0.33,0.03,-0.35,0.31
wt_mean_oct original [degC],3.74,3.96,3.36,5.41,5.30,3.42,3.79,2.84,3.36,6.05,6.24,3.16,3.26,4.83,4.37,5.77,5.13,3.60,4.80,3.80
wt_mean_oct adjusted [degC],3.35,3.81,3.08,4.85,4.69,3.01,3.26,2.57,3.25,5.38,5.61,2.80,3.04,4.36,4.19,5.21,4.61,3.37,4.35,3.56
wt_mean_oct orig-adj [degC],0.38,0.16,0.28,0.56,0.61,0.41,0.53,0.27,0.10,0.67,0.62,0.36,0.22,0.47,0.18,0.56,0.52,0.23,0.45,0.24
wt_mean_nov original [degC],2.20,3.21,1.64,2.73,2.56,1.67,1.72,1.72,2.14,3.77,3.85,1.81,1.89,2.44,2.45,3.56,2.54,1.98,2.49,2.20
wt_mean_nov adjusted [degC],2.07,3.10,1.47,2.33,2.20,1.44,1.41,1.57,2.06,3.40,3.51,1.56,1.74,2.12,2.27,3.16,2.18,1.76,2.21,2.02
wt_mean_nov orig-adj [degC],0.13,0.10,0.17,0.39,0.36,0.23,0.31,0.15,0.08,0.38,0.34,0.26,0.15,0.31,0.18,0.40,0.37,0.22,0.28,0.18
wt_mean_dec original [degC],1.95,3.01,1.37,2.10,1.92,1.26,1.24,1.49,1.90,3.03,3.15,1.47,1.61,1.93,1.99,2.85,1.92,1.56,2.02,1.87
wt_mean_dec adjusted [degC],1.94,2.97,1.27,2.00,1.83,1.23,1.06,1.40,1.86,2.90,3.04,1.34,1.60,1.85,2.00,2.71,1.81,1.58,1.95,1.87
wt_mean_dec orig-adj [degC],0.02,0.04,0.10,0.10,0.09,0.02,0.18,0.09,0.04,0.13,0.11,0.13,0.01,0.08,-0.00,0.14,0.10,-0.02,0.07,0.00

--- Annual max + 7-day rolling max ---
  rows: [variable  original], [variable  adjusted], [variable  orig-adj]

,81007640,81001892,81018674,81016686,81015222,81009538,81007044,81006011,81028553,81002342,81002209,81006462,81014892,81015857,81035388,81001992,81013581,81028376,81015018,81030542
wt_ann_max_temp_mean original [degC],13.54,12.85,14.68,13.50,13.67,13.88,14.43,13.08,10.11,16.62,17.10,13.23,12.52,13.39,12.47,17.06,13.80,10.73,13.40,12.10
wt_ann_max_temp_mean adjusted [degC],13.74,13.18,14.45,13.77,13.91,14.03,14.61,13.44,10.78,15.92,16.47,13.50,12.68,13.76,12.33,16.70,14.08,10.74,13.77,11.79
wt_ann_max_temp_mean orig-adj [degC],-0.20,-0.33,0.23,-0.27,-0.25,-0.15,-0.18,-0.36,-0.67,0.70,0.62,-0.26,-0.16,-0.37,0.14,0.36,-0.28,-0.01,-0.37,0.31
wt_ann_max_temp_doy_mean original [day of year],194.56,198.50,195.06,192.88,193.47,193.66,191.59,195.25,212.91,201.19,201.12,196.69,194.78,194.72,201.78,199.19,191.41,206.94,192.69,206.91
wt_ann_max_temp_doy_mean adjusted [day of year],198.28,199.84,203.28,200.16,201.72,196.31,195.22,200.16,214.97,206.06,206.12,198.06,199.66,205.41,204.78,204.59,199.03,204.25,202.06,208.22
wt_ann_max_temp_doy_mean orig-adj [day of year],-3.72,-1.34,-8.22,-7.28,-8.25,-2.66,-3.62,-4.91,-2.06,-4.88,-5.00,-1.38,-4.88,-10.69,-3.00,-5.41,-7.62,2.69,-9.38,-1.31
wt_7d_max_temp_mean original [degC],13.47,12.58,14.27,13.43,13.56,13.61,14.24,12.91,9.91,16.35,16.88,13.00,12.33,13.28,12.30,16.73,13.70,10.42,13.32,11.91
wt_7d_max_temp_mean adjusted [degC],13.64,12.87,14.13,13.72,13.84,13.76,14.40,13.23,10.54,15.55,16.16,13.27,12.49,13.67,12.15,16.28,13.99,10.43,13.70,11.58
wt_7d_max_temp_mean orig-adj [degC],-0.18,-0.29,0.14,-0.29,-0.27,-0.15,-0.16,-0.32,-0.63,0.80,0.72,-0.27,-0.17,-0.39,0.15,0.45,-0.29,-0.01,-0.38,0.34
wt_7d_max_temp_doy_mean original [day of year],194.78,197.19,194.19,193.34,193.22,192.38,191.09,195.72,212.03,200.62,200.78,196.22,196.09,194.28,202.72,199.38,191.19,203.81,192.56,205.78
wt_7d_max_temp_doy_mean adjusted [day of year],199.34,199.09,203.28,201.16,204.19,196.59,195.59,199.56,213.06,206.25,206.41,198.94,204.41,206.78,204.88,204.28,198.38,203.41,201.97,206.44
wt_7d_max_temp_doy_mean orig-adj [day of year],-4.56,-1.91,-9.09,-7.81,-10.97,-4.22,-4.50,-3.84,-1.03,-5.63,-5.62,-2.72,-8.31,-12.50,-2.16,-4.91,-7.19,0.41,-9.41,-0.66

--- Cumulative degree days (May–Sept) ---
  rows: [variable  original], [variable  adjusted], [variable  orig-adj]

,81007640,81001892,81018674,81016686,81015222,81009538,81007044,81006011,81028553,81002342,81002209,81006462,81014892,81015857,81035388,81001992,81013581,81028376,81015018,81030542
wt_cdd_may_sept_mean original [degC days],1517.16,1180.61,1486.58,1652.85,1659.08,1465.24,1641.18,1288.80,990.04,1593.88,1653.96,1312.60,1259.85,1578.85,1334.07,1668.37,1669.46,1084.64,1592.17,1277.27
wt_cdd_may_sept_mean adjusted [degC days],1511.68,1188.05,1451.64,1690.08,1693.57,1441.37,1638.16,1295.57,1024.82,1465.87,1501.14,1302.73,1253.69,1620.06,1283.63,1558.94,1718.88,1084.75,1644.78,1208.19
wt_cdd_may_sept_mean orig-adj [degC days],5.49,-7.44,34.94,-37.23,-34.49,23.87,3.02,-6.77,-34.78,128.01,152.83,9.87,6.16,-41.21,50.43,109.44,-49.42,-0.11,-52.61,69.07

======================================================================
  MODEL: C2LE4  |  era: 2034-2065
======================================================================

--- Threshold exceedance (days) ---
  rows: [variable  original], [variable  adjusted], [variable  orig-adj]

,81007640,81001892,81018674,81016686,81015222,81009538,81007044,81006011,81028553,81002342,81002209,81006462,81014892,81015857,81035388,81001992,81013581,81028376,81015018,81030542
wt_days_gt13_mean original [days],28 days 12:00:00,6 days 08:15:21.599999999,28 days 00:44:38.400000,24 days 02:15:21.600000,30 days 04:30:43.200000,23 days 05:15:21.600000,50 days 00:44:38.400000,8 days 10:30:43.200000,0 days,50 days 15:44:38.400000,57 days 18:00:00,10 days 14:15:21.600000,1 days 22:30:43.200000,15 days 07:29:16.800000,2 days 01:29:16.800000,57 days 09:44:38.400000,35 days 01:29:16.800000,0 days,18 days 10:30:43.200000,0 days 17:15:21.600000
wt_days_gt13_mean adjusted [days],35 days 23:15:21.600000,5 days 20:15:21.600000,28 days 02:15:21.600000,35 days 06:44:38.400000,44 days 00:00:00,26 days 09:00:00,63 days 09:00:00,8 days 12:44:38.400000,0 days,54 days 21:00:00,56 days 20:15:21.600000,10 days 11:15:21.600000,1 days 21:01:26.400000,21 days 06:00:00,2 days 01:29:16.800000,58 days 18:44:38.400000,50 days 17:15:21.600000,0 days,27 days 09:00:00,0 days 17:15:21.600000
wt_days_gt13_mean orig-adj [days],-8 days +12:44:38.400000,0 days 11:59:59.999999999,-1 days +22:29:16.800000,-12 days +19:30:43.200000,-14 days +04:30:43.200000,-4 days +20:15:21.600000,-14 days +15:44:38.400000,-1 days +21:46:04.800000,0 days,-5 days +18:44:38.400000,0 days 21:44:38.400000,0 days 03:00:00,0 days 01:29:16.800000,-6 days +01:29:16.800000,0 days 00:00:00,-2 days +15:00:00,-16 days +08:13:55.200000,0 days,-9 days +01:30:43.200000,0 days 00:00:00
wt_days_gt18_mean original [days],0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,1 days 06:00:00,2 days 12:44:38.400000,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,2 days 03:44:38.400000,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00
wt_days_gt18_mean adjusted [days],0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,1 days 06:00:00,2 days 07:29:16.800000,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,1 days 21:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00
wt_days_gt18_mean orig-adj [days],0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 05:15:21.600000,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 06:44:38.400000,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00
wt_days_gt20_mean original [days],0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00
wt_days_gt20_mean adjusted [days],0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00
wt_days_gt20_mean orig-adj [days],0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00

--- Monthly mean temperatures ---
  rows: [variable  original], [variable  adjusted], [variable  orig-adj]

,81007640,81001892,81018674,81016686,81015222,81009538,81007044,81006011,81028553,81002342,81002209,81006462,81014892,81015857,81035388,81001992,81013581,81028376,81015018,81030542
wt_mean_jan original [degC],2.09,3.36,1.56,2.30,2.07,1.36,1.34,1.61,2.14,3.19,3.36,1.60,1.75,2.13,2.13,3.06,2.10,1.72,2.20,2.05
wt_mean_jan adjusted [degC],2.07,3.29,1.43,2.15,1.96,1.32,1.17,1.51,2.02,3.05,3.23,1.49,1.73,1.98,2.16,2.86,1.97,1.66,2.08,2.00
wt_mean_jan orig-adj [degC],0.03,0.07,0.14,0.15,0.11,0.04,0.17,0.10,0.12,0.14,0.13,0.11,0.03,0.15,-0.02,0.20,0.14,0.06,0.12,0.05
wt_mean_feb original [degC],1.94,3.04,1.51,2.15,1.94,1.33,1.30,1.52,2.01,2.83,3.00,1.49,1.66,2.01,1.98,2.73,1.99,1.67,2.05,1.93
wt_mean_feb adjusted [degC],1.93,3.00,1.42,2.07,1.88,1.30,1.21,1.48,1.95,2.81,2.97,1.44,1.64,1.94,1.96,2.68,1.92,1.62,2.00,1.88
wt_mean_feb orig-adj [degC],0.02,0.05,0.10,0.08,0.06,0.03,0.08,0.04,0.07,0.03,0.03,0.05,0.02,0.07,0.02,0.05,0.08,0.05,0.06,0.06
wt_mean_mar original [degC],1.98,3.04,1.78,2.36,2.14,1.55,1.55,1.64,2.04,2.87,3.01,1.63,1.78,2.20,2.06,2.80,2.21,1.80,2.21,2.01
wt_mean_mar adjusted [degC],1.95,3.00,1.62,2.19,2.02,1.56,1.41,1.60,1.90,2.85,2.99,1.56,1.72,2.04,2.02,2.76,2.05,1.64,2.08,1.88
wt_mean_mar orig-adj [degC],0.02,0.03,0.15,0.17,0.12,-0.01,0.15,0.05,0.14,0.02,0.02,0.07,0.06,0.16,0.04,0.03,0.15,0.16,0.12,0.13
wt_mean_apr original [degC],2.40,3.26,2.67,3.61,3.34,2.33,2.56,2.06,2.39,3.36,3.41,2.10,2.27,3.31,2.53,3.46,3.44,2.42,3.24,2.50
wt_mean_apr adjusted [degC],2.42,3.29,2.74,3.67,3.42,2.41,2.59,2.07,2.35,3.34,3.36,2.14,2.34,3.37,2.53,3.45,3.60,2.46,3.30,2.48
wt_mean_apr orig-adj [degC],-0.03,-0.03,-0.07,-0.06,-0.08,-0.08,-0.02,-0.01,0.04,0.03,0.05,-0.04,-0.07,-0.06,0.00,0.01,-0.16,-0.04,-0.06,0.03
wt_mean_may original [degC],6.11,4.59,5.90,7.93,7.95,5.71,7.18,4.33,3.71,5.08,4.96,4.67,4.66,7.22,4.65,5.65,7.99,4.13,7.38,4.65
wt_mean_may adjusted [degC],6.10,4.58,5.61,8.40,8.43,5.60,7.23,4.29,3.73,5.03,4.85,4.56,4.65,7.61,4.52,5.48,8.55,4.13,7.85,4.52
wt_mean_may orig-adj [degC],0.01,0.00,0.29,-0.46,-0.48,0.10,-0.05,0.04,-0.03,0.05,0.11,0.11,0.01,-0.39,0.12,0.16,-0.56,-0.00,-0.46,0.13
wt_mean_jun original [degC],11.53,8.26,11.02,11.91,12.13,11.02,12.60,9.89,6.16,10.46,10.62,9.97,9.17,11.40,8.95,11.54,12.24,6.71,11.61,8.51
wt_mean_jun adjusted [degC],11.31,7.98,10.44,12.20,12.28,10.66,12.54,9.74,6.42,9.23,8.99,9.57,8.90,11.67,8.32,10.07,12.61,6.78,11.96,7.88
wt_mean_jun orig-adj [degC],0.22,0.28,0.57,-0.29,-0.16,0.36,0.05,0.15,-0.26,1.24,1.64,0.41,0.27,-0.27,0.63,1.47,-0.38,-0.08,-0.34,0.62
wt_mean_jul original [degC],12.85,10.90,13.05,12.73,12.89,12.69,13.60,11.92,8.13,14.55,15.16,11.93,11.14,12.42,11.23,15.00,12.96,8.79,12.53,10.84
wt_mean_jul adjusted [degC],13.49,11.62,13.34,13.73,13.92,13.23,14.26,12.90,9.25,14.61,14.53,12.49,11.83,13.53,11.26,15.12,13.99,9.57,13.69,10.73
wt_mean_jul orig-adj [degC],-0.64,-0.72,-0.29,-1.00,-1.03,-0.54,-0.65,-0.98,-1.12,-0.05,0.63,-0.56,-0.70,-1.11,-0.02,-0.12,-1.03,-0.78,-1.16,0.11
wt_mean_aug original [degC],11.49,9.33,11.54,11.88,12.01,11.05,12.10,10.19,8.14,12.95,13.63,10.15,9.82,11.49,11.11,13.19,11.89,9.06,11.54,10.63
wt_mean_aug adjusted [degC],12.48,10.06,12.03,13.00,13.16,11.80,13.09,11.24,9.00,13.36,13.87,11.07,10.65,12.66,11.24,13.74,13.12,9.55,12.84,10.49
wt_mean_aug orig-adj [degC],-0.99,-0.73,-0.50,-1.12,-1.16,-0.74,-0.99,-1.05,-0.86,-0.41,-0.24,-0.92,-0.83,-1.17,-0.14,-0.55,-1.23,-0.49,-1.29,0.14
wt_mean_sep original [degC],7.26,5.76,6.90,9.17,9.19,6.78,7.76,5.71,5.56,9.15,9.66,5.92,5.93,8.53,7.82,9.11,8.88,6.33,8.52,6.96
wt_mean_sep adjusted [degC],7.66,5.91,6.87,9.71,9.71,6.88,8.28,5.97,5.83,9.01,9.46,6.23,6.03,9.04,7.61,9.12,9.50,6.38,9.14,6.57
wt_mean_sep orig-adj [degC],-0.40,-0.14,0.04,-0.54,-0.52,-0.10,-0.51,-0.26,-0.27,0.14,0.20,-0.31,-0.10,-0.52,0.21,-0.01,-0.63,-0.05,-0.62,0.39
wt_mean_oct original [degC],3.66,3.81,3.19,5.13,5.13,3.30,3.67,2.76,3.06,6.00,6.15,3.07,3.06,4.54,4.25,5.64,4.83,3.36,4.55,3.58
wt_mean_oct adjusted [degC],3.22,3.60,2.77,4.44,4.44,2.77,3.09,2.45,2.84,5.42,5.57,2.65,2.72,3.96,3.88,5.06,4.17,3.03,3.98,3.19
wt_mean_oct orig-adj [degC],0.44,0.22,0.43,0.69,0.69,0.53,0.58,0.31,0.22,0.58,0.58,0.42,0.34,0.58,0.37,0.58,0.66,0.32,0.57,0.39
wt_mean_nov original [degC],2.21,3.20,1.65,2.78,2.60,1.68,1.74,1.73,2.13,3.83,3.89,1.83,1.87,2.49,2.38,3.58,2.56,1.93,2.51,2.20
wt_mean_nov adjusted [degC],2.11,3.15,1.51,2.45,2.29,1.53,1.52,1.64,2.09,3.63,3.68,1.66,1.76,2.25,2.28,3.34,2.29,1.80,2.28,2.10
wt_mean_nov orig-adj [degC],0.10,0.06,0.14,0.33,0.30,0.15,0.22,0.09,0.03,0.20,0.21,0.17,0.10,0.24,0.10,0.24,0.27,0.12,0.23,0.10
wt_mean_dec original [degC],1.96,3.04,1.44,2.12,1.93,1.29,1.26,1.50,1.91,3.07,3.19,1.49,1.63,1.96,1.99,2.89,1.95,1.58,2.03,1.88
wt_mean_dec adjusted [degC],1.95,3.01,1.31,2.04,1.86,1.28,1.14,1.43,1.87,3.03,3.15,1.40,1.61,1.90,1.98,2.82,1.87,1.54,1.98,1.85
wt_mean_dec orig-adj [degC],0.01,0.02,0.14,0.08,0.07,0.02,0.12,0.06,0.04,0.04,0.04,0.09,0.02,0.06,0.01,0.06,0.08,0.03,0.05,0.03

--- Annual max + 7-day rolling max ---
  rows: [variable  original], [variable  adjusted], [variable  orig-adj]

,81007640,81001892,81018674,81016686,81015222,81009538,81007044,81006011,81028553,81002342,81002209,81006462,81014892,81015857,81035388,81001992,81013581,81028376,81015018,81030542
wt_ann_max_temp_mean original [degC],13.47,12.77,14.60,13.39,13.58,13.81,14.39,13.00,9.91,16.72,17.16,13.20,12.37,13.25,12.61,17.17,13.67,10.75,13.27,12.21
wt_ann_max_temp_mean adjusted [degC],13.81,13.26,14.57,13.92,14.10,14.13,14.69,13.54,10.87,16.75,17.05,13.55,12.76,13.93,12.51,17.37,14.18,11.17,13.92,11.95
wt_ann_max_temp_mean orig-adj [degC],-0.34,-0.50,0.03,-0.53,-0.52,-0.32,-0.30,-0.54,-0.96,-0.03,0.11,-0.35,-0.39,-0.68,0.10,-0.19,-0.51,-0.42,-0.65,0.27
wt_ann_max_temp_doy_mean original [day of year],196.44,202.00,197.72,198.41,197.09,194.00,191.62,198.66,212.97,200.09,201.38,196.88,198.47,199.00,212.03,199.69,196.12,215.31,198.91,210.09
wt_ann_max_temp_doy_mean adjusted [day of year],201.47,204.72,200.00,201.09,202.47,196.72,192.69,202.81,213.06,204.41,208.41,201.44,203.31,206.12,215.34,206.22,200.72,211.59,206.88,209.50
wt_ann_max_temp_doy_mean orig-adj [day of year],-5.03,-2.72,-2.28,-2.69,-5.38,-2.72,-1.06,-4.16,-0.09,-4.31,-7.03,-4.56,-4.84,-7.12,-3.31,-6.53,-4.59,3.72,-7.97,0.59
wt_7d_max_temp_mean original [degC],13.40,12.48,14.20,13.31,13.48,13.52,14.17,12.81,9.71,16.41,16.93,12.96,12.15,13.13,12.44,16.84,13.56,10.45,13.18,12.03
wt_7d_max_temp_mean adjusted [degC],13.77,12.98,14.27,13.86,14.01,13.87,14.50,13.38,10.61,16.45,16.83,13.32,12.61,13.82,12.35,17.05,14.08,10.86,13.85,11.77
wt_7d_max_temp_mean orig-adj [degC],-0.37,-0.50,-0.07,-0.55,-0.53,-0.35,-0.33,-0.57,-0.91,-0.04,0.10,-0.36,-0.46,-0.69,0.09,-0.21,-0.53,-0.41,-0.66,0.26
wt_7d_max_temp_doy_mean original [day of year],196.84,200.59,196.56,199.00,197.00,196.25,193.00,198.38,212.41,200.09,201.50,196.34,199.59,199.62,212.03,198.94,195.84,215.97,198.56,209.69
wt_7d_max_temp_doy_mean adjusted [day of year],202.91,205.31,199.97,202.41,204.16,202.22,195.88,202.22,211.06,205.13,209.16,200.69,204.88,207.47,211.75,203.59,201.81,210.62,206.75,210.41
wt_7d_max_temp_doy_mean orig-adj [day of year],-6.06,-4.72,-3.41,-3.41,-7.16,-5.97,-2.88,-3.84,1.34,-5.03,-7.66,-4.34,-5.28,-7.84,0.28,-4.66,-5.97,5.34,-8.19,-0.72

--- Cumulative degree days (May–Sept) ---
  rows: [variable  original], [variable  adjusted], [variable  orig-adj]

,81007640,81001892,81018674,81016686,81015222,81009538,81007044,81006011,81028553,81002342,81002209,81006462,81014892,81015857,81035388,81001992,81013581,81028376,81015018,81030542
wt_cdd_may_sept_mean original [degC days],1507.66,1189.92,1482.42,1641.45,1657.55,1447.19,1630.17,1287.73,970.71,1598.19,1654.59,1305.97,1247.15,1562.99,1339.77,1668.60,1651.49,1072.46,1579.10,1273.33
wt_cdd_may_sept_mean adjusted [degC days],1562.98,1230.74,1479.39,1745.82,1760.27,1475.47,1696.13,1352.52,1048.90,1569.47,1583.89,1345.49,1288.69,1669.07,1315.47,1640.12,1768.61,1115.65,1698.30,1231.33
wt_cdd_may_sept_mean orig-adj [degC days],-55.32,-40.82,3.03,-104.37,-102.72,-28.28,-65.95,-64.79,-78.20,28.72,70.70,-39.52,-41.54,-106.08,24.30,28.48,-117.12,-43.19,-119.20,42.00

======================================================================
  MODEL: C2LE7  |  era: 2034-2065
======================================================================

--- Threshold exceedance (days) ---
  rows: [variable  original], [variable  adjusted], [variable  orig-adj]

,81007640,81001892,81018674,81016686,81015222,81009538,81007044,81006011,81028553,81002342,81002209,81006462,81014892,81015857,81035388,81001992,81013581,81028376,81015018,81030542
wt_days_gt13_mean original [days],20 days 23:15:21.600000,5 days 05:15:21.600000,24 days 09:44:38.400000,17 days 02:15:21.600000,22 days 02:15:21.600000,18 days 09:44:38.400000,44 days 09:44:38.400000,6 days 09:00:00,0 days,45 days 09:00:00,55 days 05:15:21.600000,8 days 09:44:38.400000,2 days 07:29:16.800000,11 days 18:44:38.400000,1 days 17:15:21.600000,54 days 14:15:21.600000,26 days 06:44:38.400000,0 days,13 days 00:00:00,0 days 21:00:00
wt_days_gt13_mean adjusted [days],27 days 00:00:00,5 days 06:00:00,23 days 20:15:21.600000,25 days 22:30:43.200000,31 days 22:29:16.800000,21 days 12:44:38.400000,55 days 13:29:16.800000,7 days 05:13:55.200000,0 days,46 days 03:44:38.400000,50 days 10:29:16.800000,8 days 12:44:38.400000,2 days 09:44:38.400000,17 days 06:44:38.400000,1 days 17:15:21.600000,53 days 05:15:21.600000,37 days 21:46:04.800000,0 days,20 days 16:29:16.800000,0 days 21:00:00
wt_days_gt13_mean orig-adj [days],-7 days +23:15:21.600000,-1 days +23:15:21.600000,0 days 13:29:16.800000,-9 days +03:44:38.400000,-10 days +03:46:04.800000,-4 days +21:00:00,-12 days +20:15:21.600000,-1 days +03:46:04.800000,0 days,-1 days +05:15:21.600000,4 days 18:46:04.800000,-1 days +21:00:00,-1 days +21:44:38.400000,-6 days +12:00:00,0 days 00:00:00,1 days 09:00:00,-12 days +08:58:33.600000,0 days,-8 days +07:30:43.200000,0 days 00:00:00
wt_days_gt18_mean original [days],0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 06:44:38.400000,0 days 19:29:16.800000,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,1 days 01:29:16.800000,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00
wt_days_gt18_mean adjusted [days],0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 06:44:38.400000,0 days 19:29:16.800000,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,1 days 01:29:16.800000,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00
wt_days_gt18_mean orig-adj [days],0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00
wt_days_gt20_mean original [days],0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00
wt_days_gt20_mean adjusted [days],0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00
wt_days_gt20_mean orig-adj [days],0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00

--- Monthly mean temperatures ---
  rows: [variable  original], [variable  adjusted], [variable  orig-adj]

,81007640,81001892,81018674,81016686,81015222,81009538,81007044,81006011,81028553,81002342,81002209,81006462,81014892,81015857,81035388,81001992,81013581,81028376,81015018,81030542
wt_mean_jan original [degC],2.08,3.36,1.56,2.26,2.04,1.37,1.31,1.61,2.13,3.21,3.39,1.57,1.75,2.10,2.13,3.07,2.06,1.76,2.18,2.06
wt_mean_jan adjusted [degC],2.04,3.27,1.37,2.13,1.93,1.29,1.15,1.51,2.05,3.13,3.31,1.42,1.68,1.97,2.11,2.92,1.92,1.65,2.07,1.99
wt_mean_jan orig-adj [degC],0.05,0.09,0.19,0.13,0.11,0.08,0.16,0.10,0.08,0.08,0.07,0.15,0.07,0.13,0.03,0.15,0.14,0.11,0.11,0.07
wt_mean_feb original [degC],1.94,3.00,1.53,2.08,1.90,1.28,1.23,1.47,1.94,2.75,2.94,1.46,1.65,1.94,1.99,2.61,1.93,1.65,2.00,1.92
wt_mean_feb adjusted [degC],1.92,2.96,1.41,2.00,1.83,1.27,1.15,1.43,1.85,2.71,2.91,1.41,1.60,1.85,1.97,2.55,1.82,1.49,1.94,1.85
wt_mean_feb orig-adj [degC],0.02,0.05,0.12,0.09,0.07,0.01,0.09,0.04,0.09,0.04,0.03,0.04,0.05,0.09,0.02,0.06,0.10,0.16,0.06,0.08
wt_mean_mar original [degC],1.97,3.04,1.81,2.29,2.09,1.52,1.50,1.61,2.01,2.83,2.98,1.59,1.78,2.14,2.08,2.75,2.16,1.79,2.16,2.02
wt_mean_mar adjusted [degC],1.94,3.00,1.66,2.13,1.98,1.52,1.33,1.54,1.92,2.80,2.95,1.51,1.73,2.00,2.03,2.70,2.00,1.65,2.04,1.92
wt_mean_mar orig-adj [degC],0.03,0.04,0.16,0.16,0.11,0.00,0.17,0.07,0.09,0.03,0.03,0.09,0.05,0.14,0.04,0.05,0.15,0.14,0.11,0.09
wt_mean_apr original [degC],2.36,3.25,2.76,3.58,3.31,2.32,2.48,2.02,2.34,3.24,3.29,2.09,2.30,3.27,2.53,3.35,3.41,2.41,3.21,2.49
wt_mean_apr adjusted [degC],2.29,3.22,2.68,3.45,3.22,2.24,2.33,1.95,2.31,3.14,3.18,2.00,2.27,3.18,2.49,3.22,3.32,2.40,3.10,2.44
wt_mean_apr orig-adj [degC],0.07,0.03,0.07,0.14,0.09,0.07,0.16,0.07,0.02,0.10,0.11,0.08,0.03,0.09,0.04,0.13,0.10,0.02,0.11,0.06
wt_mean_may original [degC],5.75,4.37,5.70,7.52,7.51,5.38,6.75,3.99,3.48,4.56,4.44,4.39,4.46,6.88,4.37,5.08,7.60,3.89,6.99,4.35
wt_mean_may adjusted [degC],5.13,4.14,5.17,7.57,7.57,4.71,6.18,3.64,3.45,4.17,4.04,3.82,4.11,6.90,4.11,4.40,7.62,3.77,7.03,4.00
wt_mean_may orig-adj [degC],0.62,0.23,0.54,-0.05,-0.05,0.67,0.57,0.35,0.03,0.39,0.40,0.57,0.35,-0.02,0.26,0.67,-0.02,0.12,-0.04,0.35
wt_mean_jun original [degC],11.43,7.97,10.85,11.83,12.03,10.95,12.52,9.71,6.06,9.72,9.81,9.78,9.10,11.31,8.69,11.17,12.14,6.70,11.53,8.43
wt_mean_jun adjusted [degC],10.88,7.40,9.92,11.79,11.92,10.15,12.16,9.14,6.15,7.85,7.57,8.82,8.37,11.23,7.68,9.15,12.17,6.53,11.52,7.46
wt_mean_jun orig-adj [degC],0.55,0.57,0.92,0.04,0.11,0.80,0.36,0.57,-0.09,1.87,2.24,0.96,0.73,0.07,1.01,2.02,-0.02,0.17,0.01,0.97
wt_mean_jul original [degC],12.58,10.24,12.82,12.31,12.45,12.37,13.29,11.45,7.75,13.91,14.62,11.61,10.87,11.98,10.96,14.42,12.56,8.41,12.07,10.69
wt_mean_jul adjusted [degC],13.15,10.83,12.92,13.15,13.31,12.91,13.90,12.33,8.71,13.77,14.01,12.09,11.44,12.94,10.78,14.60,13.46,9.09,13.07,10.55
wt_mean_jul orig-adj [degC],-0.57,-0.60,-0.10,-0.84,-0.86,-0.53,-0.61,-0.88,-0.95,0.14,0.61,-0.48,-0.57,-0.96,0.18,-0.18,-0.89,-0.68,-1.00,0.14
wt_mean_aug original [degC],11.39,9.20,11.39,11.71,11.78,11.08,12.04,10.02,7.95,12.98,13.70,10.14,9.67,11.33,10.86,13.26,11.76,8.74,11.35,10.37
wt_mean_aug adjusted [degC],12.34,10.03,12.02,12.71,12.79,11.89,12.91,11.06,8.74,13.39,14.05,11.17,10.62,12.39,11.19,13.88,12.85,9.38,12.52,10.49
wt_mean_aug orig-adj [degC],-0.95,-0.83,-0.63,-1.00,-1.01,-0.81,-0.87,-1.04,-0.79,-0.41,-0.35,-1.03,-0.95,-1.06,-0.32,-0.63,-1.09,-0.64,-1.17,-0.13
wt_mean_sep original [degC],7.42,5.85,7.05,9.06,9.06,6.97,7.97,5.86,5.59,9.30,9.84,6.11,6.03,8.44,7.93,9.30,8.85,6.30,8.44,7.00
wt_mean_sep adjusted [degC],7.51,5.83,6.95,9.48,9.45,6.85,8.12,5.88,5.92,8.77,9.27,6.07,6.03,8.87,7.86,8.95,9.35,6.42,8.94,6.73
wt_mean_sep orig-adj [degC],-0.08,0.02,0.10,-0.42,-0.39,0.12,-0.15,-0.02,-0.33,0.53,0.57,0.04,0.00,-0.42,0.07,0.35,-0.50,-0.12,-0.50,0.26
wt_mean_oct original [degC],3.47,3.73,3.09,4.90,4.87,3.13,3.49,2.62,3.03,5.82,5.98,2.90,2.95,4.33,4.17,5.43,4.63,3.33,4.34,3.54
wt_mean_oct adjusted [degC],3.09,3.54,2.80,4.38,4.30,2.69,2.95,2.32,2.96,5.02,5.17,2.51,2.72,3.92,3.98,4.70,4.16,3.13,3.94,3.29
wt_mean_oct orig-adj [degC],0.38,0.18,0.29,0.52,0.56,0.45,0.54,0.30,0.06,0.80,0.81,0.39,0.23,0.42,0.20,0.73,0.47,0.20,0.40,0.25
wt_mean_nov original [degC],2.20,3.20,1.65,2.77,2.58,1.68,1.74,1.73,2.15,3.76,3.82,1.82,1.86,2.48,2.47,3.50,2.52,1.98,2.51,2.24
wt_mean_nov adjusted [degC],2.10,3.12,1.48,2.48,2.31,1.51,1.50,1.62,2.12,3.44,3.54,1.62,1.74,2.26,2.39,3.19,2.24,1.84,2.31,2.16
wt_mean_nov orig-adj [degC],0.09,0.07,0.17,0.28,0.28,0.17,0.24,0.10,0.03,0.31,0.28,0.20,0.12,0.22,0.08,0.31,0.28,0.14,0.20,0.08
wt_mean_dec original [degC],1.97,3.03,1.42,2.14,1.94,1.29,1.27,1.50,1.92,3.03,3.16,1.50,1.62,1.96,2.00,2.87,1.97,1.60,2.04,1.88
wt_mean_dec adjusted [degC],1.94,2.98,1.26,2.02,1.84,1.23,1.09,1.40,1.86,2.92,3.07,1.36,1.57,1.86,1.97,2.72,1.84,1.53,1.96,1.82
wt_mean_dec orig-adj [degC],0.02,0.05,0.16,0.12,0.10,0.06,0.18,0.10,0.06,0.11,0.09,0.14,0.04,0.10,0.03,0.15,0.13,0.07,0.08,0.06

--- Annual max + 7-day rolling max ---
  rows: [variable  original], [variable  adjusted], [variable  orig-adj]

,81007640,81001892,81018674,81016686,81015222,81009538,81007044,81006011,81028553,81002342,81002209,81006462,81014892,81015857,81035388,81001992,81013581,81028376,81015018,81030542
wt_ann_max_temp_mean original [degC],13.42,12.41,14.47,13.18,13.36,13.68,14.28,12.81,9.58,16.33,16.78,13.09,12.32,13.02,12.53,16.78,13.50,10.37,13.05,12.08
wt_ann_max_temp_mean adjusted [degC],13.65,12.81,14.40,13.54,13.71,13.80,14.54,13.30,10.58,16.20,16.57,13.23,12.55,13.51,12.40,16.81,13.89,10.97,13.53,12.01
wt_ann_max_temp_mean orig-adj [degC],-0.23,-0.39,0.07,-0.36,-0.36,-0.12,-0.26,-0.50,-1.00,0.13,0.21,-0.14,-0.23,-0.49,0.13,-0.03,-0.40,-0.61,-0.48,0.07
wt_ann_max_temp_doy_mean original [day of year],200.19,204.34,196.34,194.97,191.88,199.72,190.41,196.66,214.94,202.75,205.47,203.09,201.72,196.38,213.09,202.09,191.56,213.19,194.84,209.72
wt_ann_max_temp_doy_mean adjusted [day of year],201.88,207.38,204.88,198.34,197.91,202.94,198.50,198.25,217.81,208.50,213.09,207.88,208.00,203.41,213.62,211.88,196.16,215.59,202.72,209.41
wt_ann_max_temp_doy_mean orig-adj [day of year],-1.69,-3.03,-8.53,-3.38,-6.03,-3.22,-8.09,-1.59,-2.88,-5.75,-7.62,-4.78,-6.28,-7.03,-0.53,-9.78,-4.59,-2.41,-7.88,0.31
wt_7d_max_temp_mean original [degC],13.33,12.10,14.10,13.09,13.25,13.45,14.08,12.57,9.39,15.98,16.51,12.87,12.12,12.89,12.37,16.43,13.37,10.08,12.95,11.93
wt_7d_max_temp_mean adjusted [degC],13.57,12.46,14.08,13.47,13.63,13.59,14.34,13.04,10.34,15.80,16.27,13.00,12.40,13.39,12.24,16.38,13.78,10.71,13.45,11.86
wt_7d_max_temp_mean orig-adj [degC],-0.24,-0.36,0.02,-0.38,-0.38,-0.14,-0.26,-0.47,-0.94,0.19,0.25,-0.13,-0.28,-0.50,0.13,0.04,-0.41,-0.63,-0.50,0.07
wt_7d_max_temp_doy_mean original [day of year],199.62,205.34,195.06,195.41,191.78,200.53,191.09,196.56,214.16,201.12,205.06,200.88,201.97,197.78,214.44,201.59,192.22,212.44,195.16,208.44
wt_7d_max_temp_doy_mean adjusted [day of year],200.12,210.06,206.28,200.84,199.53,205.09,197.56,197.75,218.81,207.84,212.44,205.31,208.47,206.88,215.06,211.62,197.69,216.69,202.44,208.78
wt_7d_max_temp_doy_mean orig-adj [day of year],-0.50,-4.72,-11.22,-5.44,-7.75,-4.56,-6.47,-1.19,-4.66,-6.72,-7.38,-4.44,-6.50,-9.09,-0.62,-10.03,-5.47,-4.25,-7.28,-0.34

--- Cumulative degree days (May–Sept) ---
  rows: [variable  original], [variable  adjusted], [variable  orig-adj]

,81007640,81001892,81018674,81016686,81015222,81009538,81007044,81006011,81028553,81002342,81002209,81006462,81014892,81015857,81035388,81001992,81013581,81028376,81015018,81030542
wt_cdd_may_sept_mean original [degC days],1486.85,1152.32,1464.19,1604.08,1616.66,1431.43,1609.09,1256.06,944.45,1545.78,1605.00,1287.22,1228.97,1528.26,1310.19,1629.21,1619.53,1042.30,1541.68,1250.31
wt_cdd_may_sept_mean adjusted [degC days],1500.55,1171.68,1439.14,1673.96,1684.71,1424.43,1630.83,1287.97,1010.08,1469.81,1499.87,1286.22,1243.04,1601.70,1274.32,1561.92,1697.09,1078.31,1624.67,1201.96
wt_cdd_may_sept_mean orig-adj [degC days],-13.70,-19.37,25.05,-69.88,-68.05,7.00,-21.75,-31.92,-65.63,75.97,105.13,1.01,-14.07,-73.44,35.87,67.29,-77.56,-36.00,-83.00,48.35

======================================================================
  MODEL: C2LE9  |  era: 2034-2065
======================================================================

--- Threshold exceedance (days) ---
  rows: [variable  original], [variable  adjusted], [variable  orig-adj]

,81007640,81001892,81018674,81016686,81015222,81009538,81007044,81006011,81028553,81002342,81002209,81006462,81014892,81015857,81035388,81001992,81013581,81028376,81015018,81030542
wt_days_gt13_mean original [days],24 days 19:29:16.800000,5 days 19:29:16.800000,24 days,29 days 22:30:43.200000,33 days 12:00:00,20 days 16:30:43.199999999,48 days 13:29:16.800000,8 days 12:00:00,0 days,52 days 14:15:21.600000,61 days 18:44:38.400000,9 days 06:00:00,2 days 18:44:38.400000,19 days 14:15:21.600000,2 days 18:00:00,60 days 10:30:43.200000,36 days 06:44:38.400000,0 days,23 days 21:00:00,0 days 20:15:21.600000
wt_days_gt13_mean adjusted [days],29 days 02:58:33.600000,5 days 04:29:16.800000,22 days,37 days 13:30:43.199999999,41 days 11:15:21.600000,22 days 00:46:04.800000,54 days 11:58:33.600000,8 days 00:00:00,0 days,47 days 13:30:43.199999999,53 days 08:13:55.200000,8 days 06:00:00,2 days 15:44:38.400000,23 days 09:46:04.799999999,2 days 18:00:00,54 days 15:46:04.800000,45 days 06:00:00,0 days,30 days 01:29:16.800000,0 days 20:15:21.600000
wt_days_gt13_mean orig-adj [days],-5 days +16:30:43.200000,0 days 15:00:00,2 days,-8 days +09:00:00.000000001,-8 days +00:44:38.400000,-2 days +15:44:38.399999999,-6 days +01:30:43.200000,0 days 12:00:00,0 days,5 days 00:44:38.400000001,8 days 10:30:43.200000,1 days 00:00:00,0 days 03:00:00,-4 days +04:29:16.800000001,0 days 00:00:00,5 days 18:44:38.400000,-9 days +00:44:38.400000,0 days,-7 days +19:30:43.200000,0 days 00:00:00
wt_days_gt18_mean original [days],0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,1 days 03:44:38.400000,1 days 21:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,1 days 23:15:21.600000,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00
wt_days_gt18_mean adjusted [days],0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,1 days 03:44:38.400000,1 days 21:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,1 days 23:15:21.600000,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00
wt_days_gt18_mean orig-adj [days],0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00
wt_days_gt20_mean original [days],0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00
wt_days_gt20_mean adjusted [days],0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00
wt_days_gt20_mean orig-adj [days],0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days,0 days 00:00:00,0 days 00:00:00

--- Monthly mean temperatures ---
  rows: [variable  original], [variable  adjusted], [variable  orig-adj]

,81007640,81001892,81018674,81016686,81015222,81009538,81007044,81006011,81028553,81002342,81002209,81006462,81014892,81015857,81035388,81001992,81013581,81028376,81015018,81030542
wt_mean_jan original [degC],2.15,3.48,1.66,2.43,2.19,1.46,1.44,1.68,2.25,3.31,3.47,1.69,1.83,2.26,2.19,3.24,2.25,1.90,2.31,2.17
wt_mean_jan adjusted [degC],2.12,3.38,1.51,2.34,2.11,1.42,1.34,1.62,2.18,3.27,3.45,1.58,1.79,2.16,2.18,3.15,2.14,1.81,2.24,2.11
wt_mean_jan orig-adj [degC],0.03,0.10,0.14,0.10,0.07,0.04,0.10,0.06,0.07,0.03,0.01,0.11,0.04,0.09,0.02,0.09,0.10,0.09,0.07,0.05
wt_mean_feb original [degC],1.95,3.05,1.54,2.15,1.94,1.34,1.27,1.52,2.01,2.81,2.98,1.49,1.68,2.00,1.99,2.73,2.00,1.72,2.05,1.95
wt_mean_feb adjusted [degC],1.93,2.99,1.41,2.09,1.88,1.27,1.16,1.45,1.93,2.75,2.94,1.42,1.63,1.93,1.98,2.64,1.91,1.61,2.00,1.90
wt_mean_feb orig-adj [degC],0.02,0.06,0.14,0.07,0.06,0.07,0.10,0.06,0.08,0.06,0.04,0.07,0.05,0.07,0.01,0.10,0.09,0.11,0.05,0.05
wt_mean_mar original [degC],2.01,3.09,1.91,2.53,2.27,1.63,1.61,1.67,2.10,2.92,3.06,1.68,1.85,2.35,2.13,2.90,2.35,1.92,2.32,2.12
wt_mean_mar adjusted [degC],1.99,3.05,1.77,2.38,2.15,1.60,1.46,1.60,1.99,2.87,3.02,1.60,1.78,2.21,2.09,2.83,2.20,1.75,2.21,2.02
wt_mean_mar orig-adj [degC],0.02,0.04,0.14,0.15,0.11,0.03,0.15,0.06,0.11,0.05,0.04,0.08,0.07,0.14,0.04,0.07,0.15,0.17,0.11,0.10
wt_mean_apr original [degC],2.40,3.27,2.81,3.83,3.48,2.38,2.52,2.03,2.37,3.26,3.31,2.13,2.37,3.48,2.61,3.36,3.60,2.44,3.38,2.58
wt_mean_apr adjusted [degC],2.29,3.20,2.67,3.47,3.19,2.27,2.31,1.95,2.26,3.17,3.23,2.03,2.28,3.20,2.48,3.22,3.32,2.34,3.10,2.41
wt_mean_apr orig-adj [degC],0.10,0.07,0.14,0.36,0.29,0.11,0.20,0.09,0.11,0.10,0.08,0.09,0.09,0.28,0.12,0.15,0.28,0.10,0.27,0.16
wt_mean_may original [degC],6.06,4.54,5.89,8.08,8.00,5.69,7.17,4.31,3.55,5.04,4.87,4.60,4.66,7.38,4.55,5.62,8.18,4.01,7.52,4.58
wt_mean_may adjusted [degC],5.64,4.46,5.56,8.03,7.98,5.31,6.77,4.11,3.53,4.74,4.55,4.25,4.48,7.35,4.38,5.19,8.22,3.93,7.48,4.35
wt_mean_may orig-adj [degC],0.42,0.08,0.32,0.05,0.02,0.38,0.40,0.20,0.03,0.30,0.31,0.35,0.18,0.04,0.18,0.44,-0.05,0.08,0.04,0.23
wt_mean_jun original [degC],11.49,8.14,10.91,12.10,12.23,10.98,12.60,9.88,6.33,11.00,11.23,9.84,9.24,11.62,8.92,12.07,12.38,6.87,11.80,8.62
wt_mean_jun adjusted [degC],11.39,7.96,10.46,12.02,12.17,10.69,12.56,9.76,6.26,9.47,9.49,9.55,8.99,11.52,8.26,10.56,12.52,6.70,11.79,7.95
wt_mean_jun orig-adj [degC],0.11,0.17,0.46,0.08,0.05,0.29,0.04,0.12,0.07,1.53,1.74,0.29,0.25,0.11,0.66,1.51,-0.14,0.18,0.01,0.67
wt_mean_jul original [degC],12.80,10.85,12.92,12.85,12.97,12.61,13.54,11.89,8.22,14.75,15.34,11.77,11.20,12.56,11.12,15.03,13.06,8.90,12.65,10.83
wt_mean_jul adjusted [degC],13.15,11.20,12.92,13.29,13.46,12.87,13.90,12.43,8.87,14.28,14.41,12.09,11.51,13.07,10.90,14.90,13.59,9.33,13.20,10.44
wt_mean_jul orig-adj [degC],-0.35,-0.35,0.00,-0.44,-0.49,-0.26,-0.35,-0.53,-0.65,0.46,0.93,-0.32,-0.31,-0.51,0.23,0.13,-0.53,-0.43,-0.54,0.39
wt_mean_aug original [degC],11.55,9.10,11.48,12.04,12.12,11.22,12.17,10.19,8.10,12.91,13.62,10.16,9.82,11.67,11.04,13.22,12.09,8.93,11.73,10.56
wt_mean_aug adjusted [degC],12.45,9.74,12.04,12.97,13.08,11.97,13.09,11.14,9.05,13.15,13.79,10.99,10.63,12.67,11.34,13.64,13.12,9.64,12.81,10.66
wt_mean_aug orig-adj [degC],-0.91,-0.63,-0.56,-0.93,-0.96,-0.75,-0.92,-0.95,-0.94,-0.24,-0.16,-0.83,-0.82,-1.00,-0.30,-0.42,-1.04,-0.71,-1.08,-0.11
wt_mean_sep original [degC],7.49,5.89,7.18,9.36,9.38,6.98,7.99,5.86,5.68,9.48,10.00,6.13,6.13,8.69,8.12,9.49,9.13,6.41,8.75,7.21
wt_mean_sep adjusted [degC],7.86,6.06,7.26,9.95,9.95,7.12,8.46,6.06,6.02,9.16,9.73,6.37,6.35,9.27,8.19,9.45,9.87,6.61,9.44,7.04
wt_mean_sep orig-adj [degC],-0.37,-0.17,-0.08,-0.58,-0.57,-0.13,-0.47,-0.21,-0.33,0.32,0.27,-0.24,-0.21,-0.59,-0.07,0.04,-0.74,-0.20,-0.68,0.18
wt_mean_oct original [degC],3.60,3.84,3.19,5.13,5.07,3.25,3.62,2.72,3.09,6.04,6.23,3.04,3.04,4.51,4.19,5.75,4.83,3.35,4.54,3.49
wt_mean_oct adjusted [degC],3.24,3.68,3.04,4.66,4.56,2.86,3.16,2.46,3.02,5.33,5.55,2.71,2.86,4.12,4.11,5.12,4.39,3.20,4.17,3.32
wt_mean_oct orig-adj [degC],0.35,0.16,0.15,0.47,0.51,0.39,0.46,0.25,0.07,0.71,0.68,0.33,0.18,0.38,0.08,0.63,0.43,0.14,0.38,0.17
wt_mean_nov original [degC],2.19,3.18,1.59,2.81,2.63,1.63,1.71,1.71,2.18,3.81,3.88,1.78,1.86,2.50,2.35,3.54,2.55,1.95,2.54,2.17
wt_mean_nov adjusted [degC],2.11,3.12,1.55,2.55,2.38,1.50,1.47,1.61,2.16,3.53,3.63,1.60,1.78,2.30,2.32,3.27,2.31,1.87,2.36,2.12
wt_mean_nov orig-adj [degC],0.08,0.06,0.04,0.26,0.25,0.13,0.24,0.11,0.02,0.28,0.25,0.19,0.07,0.20,0.03,0.27,0.24,0.07,0.18,0.06
wt_mean_dec original [degC],1.99,3.05,1.46,2.23,2.02,1.33,1.33,1.54,1.99,3.12,3.23,1.54,1.66,2.04,2.03,2.95,2.05,1.66,2.11,1.94
wt_mean_dec adjusted [degC],1.96,3.00,1.37,2.15,1.95,1.27,1.17,1.44,1.95,3.01,3.15,1.41,1.62,1.97,2.02,2.81,1.95,1.64,2.05,1.91
wt_mean_dec orig-adj [degC],0.02,0.05,0.08,0.09,0.07,0.06,0.16,0.10,0.03,0.11,0.08,0.13,0.04,0.07,0.01,0.14,0.10,0.02,0.06,0.03

--- Annual max + 7-day rolling max ---
  rows: [variable  original], [variable  adjusted], [variable  orig-adj]

,81007640,81001892,81018674,81016686,81015222,81009538,81007044,81006011,81028553,81002342,81002209,81006462,81014892,81015857,81035388,81001992,81013581,81028376,81015018,81030542
wt_ann_max_temp_mean original [degC],13.50,12.75,14.56,13.45,13.63,13.77,14.42,13.03,9.90,16.74,17.09,13.08,12.39,13.32,12.60,17.07,13.75,10.81,13.36,12.23
wt_ann_max_temp_mean adjusted [degC],13.64,12.92,14.42,13.61,13.83,13.82,14.57,13.30,10.73,16.21,16.59,13.21,12.50,13.58,12.54,16.90,13.97,11.28,13.60,11.92
wt_ann_max_temp_mean orig-adj [degC],-0.14,-0.17,0.15,-0.16,-0.20,-0.06,-0.15,-0.27,-0.82,0.52,0.50,-0.13,-0.10,-0.26,0.06,0.17,-0.22,-0.47,-0.24,0.31
wt_ann_max_temp_doy_mean original [day of year],195.31,199.81,198.41,194.75,194.16,195.22,192.19,195.78,210.94,195.28,197.31,196.53,197.00,197.09,213.00,193.47,192.69,209.03,194.34,210.22
wt_ann_max_temp_doy_mean adjusted [day of year],192.16,201.34,202.22,198.47,198.41,190.84,191.00,193.72,218.56,197.47,200.53,195.34,197.97,208.00,218.59,198.47,197.41,212.84,203.19,217.03
wt_ann_max_temp_doy_mean orig-adj [day of year],3.16,-1.53,-3.81,-3.72,-4.25,4.38,1.19,2.06,-7.63,-2.19,-3.22,1.19,-0.97,-10.91,-5.59,-5.00,-4.72,-3.81,-8.84,-6.81
wt_7d_max_temp_mean original [degC],13.41,12.39,14.09,13.39,13.55,13.49,14.22,12.84,9.70,16.38,16.80,12.82,12.22,13.22,12.44,16.67,13.66,10.49,13.29,12.04
wt_7d_max_temp_mean adjusted [degC],13.54,12.49,13.98,13.55,13.74,13.52,14.37,13.06,10.47,15.79,16.23,12.91,12.35,13.47,12.36,16.40,13.88,10.97,13.52,11.74
wt_7d_max_temp_mean orig-adj [degC],-0.14,-0.10,0.11,-0.16,-0.20,-0.03,-0.14,-0.23,-0.77,0.59,0.57,-0.09,-0.13,-0.25,0.08,0.28,-0.22,-0.48,-0.23,0.30
wt_7d_max_temp_doy_mean original [day of year],195.12,199.41,196.12,194.38,193.94,194.75,191.50,195.06,211.94,197.06,196.53,196.50,197.38,193.16,213.31,194.66,193.16,208.66,193.56,208.59
wt_7d_max_temp_doy_mean adjusted [day of year],194.16,203.75,201.69,199.69,199.53,192.81,190.25,191.12,219.56,199.62,200.25,197.97,198.19,203.72,217.12,198.31,197.50,215.38,202.19,213.97
wt_7d_max_temp_doy_mean orig-adj [day of year],0.97,-4.34,-5.56,-5.31,-5.59,1.94,1.25,3.94,-7.62,-2.56,-3.72,-1.47,-0.81,-10.56,-3.81,-3.66,-4.34,-6.72,-8.62,-5.37

--- Cumulative degree days (May–Sept) ---
  rows: [variable  original], [variable  adjusted], [variable  orig-adj]

,81007640,81001892,81018674,81016686,81015222,81009538,81007044,81006011,81028553,81002342,81002209,81006462,81014892,81015857,81035388,81001992,81013581,81028376,81015018,81030542
wt_cdd_may_sept_mean original [degC days],1512.10,1180.31,1481.66,1665.82,1674.19,1454.53,1637.27,1290.18,976.51,1628.11,1685.61,1301.15,1257.40,1589.08,1339.33,1697.09,1678.38,1075.19,1605.69,1280.26
wt_cdd_may_sept_mean adjusted [degC days],1545.68,1208.02,1477.53,1721.62,1733.75,1468.84,1677.06,1332.31,1032.78,1556.21,1591.71,1324.52,1285.30,1649.05,1318.40,1645.56,1754.70,1108.69,1674.62,1238.40
wt_cdd_may_sept_mean orig-adj [degC days],-33.58,-27.71,4.12,-55.80,-59.56,-14.31,-39.79,-42.12,-56.27,71.90,93.90,-23.38,-27.90,-59.97,20.93,51.52,-76.32,-33.50,-68.93,41.86

In [ ]:

# Cross-model summary: orig − adj for annual max temperature
# One row per GCM model, columns are the 20 sampled stream IDs.
# Shows at a glance whether divergence between sources is consistent across models.
summary_rows = {}
for model in GCM_MODELS:
    orig = ds['wt_ann_max_temp_mean'].sel(model=model, era='2034-2065', source='original_gcm').sel(stream_id=sample_ids).values
    adj  = ds['wt_ann_max_temp_mean'].sel(model=model, era='2034-2065', source='gcm_diff_applied_to_blaskey').sel(stream_id=sample_ids).values
    summary_rows[model] = orig - adj

summary_df = pd.DataFrame(summary_rows, index=sample_ids).T
summary_df.index.name = 'model'
print('orig − adj for wt_ann_max_temp_mean  [degC]  (2034-2065)')
display(summary_df)